title: Web genial
author: Manex Agirre
email: manex.agirre@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
theme: minima

# social links
github_username:  manexagirre # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principal
