title: Portafolio de MANEX AGIRRE
author: MANEX AGIRRE
email: manex.agirre@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Este sitio está creado en la asignatura de Web. 
# social links
github_username: manexagirre # NO incluyas el carácter @ ¡o la compilación fallará!    

show_excerpts: true 
theme: minima
